name: speaker_diarization

channels:
- anaconda 
- conda-forge
- pytorch

dependencies:
# Essential
- python==3.7
- numpy==1.18.1
- scipy==1.3.1
- pandas==0.25.3
- tqdm==4.41.1
- pip==19.2.3
# Visualization
- matplotlib==3.1.1
# ML & DL
- scikit-learn==0.22.1
- pytorch==1.4.0
# NLP & Speech
- librosa==0.7.2
# Jupyter integration
- nb_conda_kernels==2.2.2
- ipython==7.1.1
- ipywidgets====7.5.1

- pip:
  - jcopdl==1.0.0
